version: "2"
services:
  web:
    build: .
    ports:
      - "8080:1337"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongo
      - MONGO_PORT_27017_TCP_PORT=27017
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=someRandomPassword
    volumes:
      - ./app:/server # volume in host -> $(pwd)/app
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    command: mongod
    ports:
      - "27017:27017"